apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-website
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/satyammsingh7-cloud/app.git
    targetRevision: main
    path: app

  destination:
    server: https://kubernetes.default.svc
    namespace: movie-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
