apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-website
spec:
  replicas: 7
  selector:
    matchLabels:
      app: movie-website
  template:
    metadata:
      labels:
        app: movie-website
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: website
        configMap:
          name: movie-site
